-- Create sations table
CREATE TABLE
    `ttc_directory`.`stations`
    (
        `station_id` INT NOT NULL AUTO_INCREMENT ,
        `station_name` VARCHAR(50) NOT NULL ,
        `washroom` ENUM('Y','N') NOT NULL ,
        `accessibility` ENUM('Y','N') NOT NULL ,
        `streetcar` ENUM('Y','N') NOT NULL ,
        PRIMARY KEY (`station_id`)
    ) ENGINE = InnoDB;

-- Insert ttc station information
INSERT INTO `stations` (`station_name`)
VALUES
    ("Finch"),
    ("North York Centre"),
    ("Sheppard–Yonge"),
    ("York Mills"),
    ("Lawrence"),
    ("Eglinton"),
    ("Davisville"),
    ("St. Clair"),
    ("Summerhill"),
    ("Rosedale"),
    ("Bloor–Yonge"),
    ("Wellesley"),
    ("College"),
    ("Dundas"),
    ("Queen"),
    ("King"),
    ("Union"),
    ("St. Andrew"),
    ("Osgoode"),
    ("St. Patrick"),
    ("Queen's Park"),
    ("Museum"),
    ("St. George"),
    ("Spadina"),
    ("Dupont"),
    ("St. Clair West"),
    ("Eglinton West"),
    ("Glencairn"),
    ("Lawrence West"),
    ("Yorkdale"),
    ("Wilson"),
    ("Sheppard West"),
    ("Downsview Park"),
    ("Finch West"),
    ("York University"),
    ("Pioneer Village"),
    ("Highway 407"),
    ("Vaughan"),
    ("Kipling"),
    ("Islington"),
    ("Royal York"),
    ("Old Mill"),
    ("Jane"),
    ("Runnymede"),
    ("High Park"),
    ("Keele"),
    ("Dundas West"),
    ("Lansdowne"),
    ("Dufferin"),
    ("Ossington"),
    ("Christie"),
    ("Bathurst"),
    ("Bay"),
    ("Sherbourne"),
    ("Castle Frank"),
    ("Broadview"),
    ("Chester"),
    ("Pape"),
    ("Donlands"),
    ("Greenwood"),
    ("Coxwell"),
    ("Woodbine"),
    ("Main Street"),
    ("Victoria Park"),
    ("Warden"),
    ("Kennedy"),
    ("Lawrence East"),
    ("Ellesmere"),
    ("Midland"),
    ("Scarborough Centre"),
    ("McCowan"),
    ("Bayview"),
    ("Bessarion"),
    ("Leslie"),
    ("Don Mills");